openapi: 3.0.0
info:
  title: My Daily Planner API
  description: |
    This is the My Daily Planner API documentation.
  version: 0.0.1
servers:
- url: /
paths:
  /test:
    get:
      operationId: testGET
      responses:
        "200":
          description: OK
      x-swagger-router-controller: Default
components:
  schemas:
    People:
      type: object
      properties:
        first_name:
          type: string
        last_name:
          type: string
        phone_num:
          type: string
        email:
          type: string
      xml:
        name: People
    APIError:
      type: object
      properties:
        message:
          type: string
        status:
          type: number
        isPublic:
          type: boolean
